Repository flipkart-incubator/dkv, pull requests merged in 2021-07, with the labels that each got.

#79 Use goreman runner for java-tests
  .github/workflows/main.yml
  clients/java/dkv-client/src/test/resources/Procfile
  clients/java/dkv-client/src/test/resources/start_dkv.sh
  internal/master/ds_service_test.go
  internal/master/ss_service_test.go
Labels: improvement

#81 Refactor service-discovery
  .github/workflows/main.yml
  Dockerfile
  cmd/dkvsrv/main.go
  internal/discovery/client.go
  internal/discovery/client_test.go
  internal/discovery/discovery.go
  internal/discovery/discovery.ini
  internal/discovery/dkv_discovery_client_test.go
  internal/discovery/dkv_discovery_service.go
  internal/discovery/dkv_discovery_service_test.go
  internal/discovery/service.go
  internal/discovery/service_test.go
  internal/hlc/hlc_test.go
  internal/master/ds_service_test.go
  internal/master/service.go
  internal/master/ss_service_test.go
  internal/master/test_setup.go
  internal/slave/service.go
  internal/slave/service_test.go
  internal/storage/store.go
  internal/sync/raftpb/rpc.pb.go
  internal/utils/utils.go
  pkg/ctl/client.go
  pkg/ctl/inprocess.go
  pkg/serverpb/api.pb.go
  pkg/serverpb/api.proto
Labels: improvement

#78 switch to vmihailenco/msgpack for better performance
  go.mod
  go.sum
  internal/storage/rocksdb/store.go
  internal/storage/rocksdb/store_test.go
Labels: performance, ready for review

#75 TTL Snapshot Bug Fixes
  .github/workflows/main.yml
  cmd/dkvsrv/main.go
  go.mod
  internal/master/ds_service_test.go
  internal/master/service.go
  internal/slave/service.go
  internal/stats/client_test.go
  internal/storage/badger/store.go
  internal/storage/badger/store_test.go
  internal/storage/iter.go
  internal/storage/iterators/iterator.go
  internal/storage/iterators/iterator_test.go
  internal/storage/rocksdb/store.go
  internal/storage/rocksdb/store_test.go
  internal/storage/store.go
  internal/storage/utils/tar.go
  internal/storage/utils/tar_test.go
  internal/sync/repl.go
Labels: bug-fix, ready for review

#83 Streaming Snapshots
  go.mod
  go.sum
  internal/master/ds_service_test.go
  internal/storage/badger/store.go
  internal/storage/rocksdb/store.go
  internal/storage/store.go
  internal/storage/utils/tar.go
  internal/storage/utils/tar_test.go
  internal/sync/repl.go
  internal/sync/repl_test.go
Labels: improvement

#76 Service discovery changes to push and get status updates of master and slaves
  Dockerfile
  clients/java/dkv-client/pom.xml
  clients/java/dkv-client/src/test/resources/Procfile
  cmd/dkvctl/main.go
  cmd/dkvsrv/main.go
  go.mod
  go.sum
  internal/discovery/client.go
  internal/discovery/client_test.go
  internal/discovery/discovery.go
  internal/discovery/discovery.ini
  internal/discovery/service.go
  internal/discovery/service_test.go
  internal/hlc/hlc.go
  internal/hlc/hlc_test.go
  internal/master/ds_service_test.go
  internal/master/service.go
  internal/master/ss_service_test.go
  internal/slave/service.go
  internal/slave/service_test.go
  internal/storage/rocksdb/store.go
  internal/storage/rocksdb/store_test.go
  pkg/ctl/client.go
  pkg/ctl/inprocess.go
  pkg/serverpb/admin.pb.go
  pkg/serverpb/admin.proto
  pkg/serverpb/api.proto
Labels: enhancement
